const express=require('express');
const router=express.Router();
const appointmentController=require('../controllers/appointmentController');
const isAdmin=require('../middlewares/isAdmin');
const isStaff=require('../middlewares/isStaff');
router.get('/available-slots',appointmentController.getAvailableSlots);
router.post('/book',appointmentController.bookAppointment);
router.post('/validate',appointmentController.validateBeforePayment);
router.get('/my',appointmentController.getMyAppointments);
router.get('/all',appointmentController.getAllAppointments);
router.put('/:id/reschedule', appointmentController.rescheduleAppointment);
router.delete('/:id',appointmentController.cancelAppointment);
module.exports=router;